version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: postgres-batch
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres