server:
  port: 8081
spring:
  batch:
    jdbc:
      initialize-schema: always
  jpa:
    open-in-view: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    drop-first: true
    enabled: true
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    user: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    clearCheckSums: true